sonar.organization=soat13
sonar.projectKey=payment
sonar.projectName=Payment

sonar.sources=.
sonar.exclusions=**/vendor/**,**/mock/**,**/*_test.go,**/tests/**,**/scripts/**,.env*,**/*.md,**/cmd/**,**/repository.go,**/bootstrap/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
