apiVersion: v1
kind: Secret
metadata:
  name: payment-sc
  namespace: fiap
type: Opaque
stringData:
  MERCADO_PAGO_TOKEN: ${MERCADO_PAGO_TOKEN}
  MERCADO_PAGO_WEBHOOK_URL: ${MERCADO_PAGO_WEBHOOK_URL}
