name: Tests

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  tests-and-quality:
    name: Tests & Quality
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:4.4
        ports:
          - "4566:4566"
        env:
          SERVICES: sns,sqs,dynamodb
          AWS_DEFAULT_REGION: us-east-1
          DEBUG: "1"
        options: >-
          --health-cmd="curl -sf http://localhost:4566/_localstack/health || exit 1"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=30

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '1.26.1'
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Bootstrap LocalStack resources
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
        run: |
          chmod +x scripts/aws/init/ready.d/*.sh
          awslocal() { aws --endpoint-url=http://localhost:4566 "$@"; }
          export -f awslocal
          scripts/aws/init/ready.d/01-init.sh

      - name: Run tests with coverage (unit + integration)
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_REGION: us-east-1
          AWS_ENDPOINT: http://localhost:4566
          DYNAMODB_TABLE: payments
          DYNAMODB_GSI1: gsi1
        run: |
          go test -v \
            -coverpkg=./internal/... \
            -coverprofile=coverage.out \
            ./...

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.go.coverage.reportPaths=coverage.out
